//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeAutomationMVC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutomationCloud
    {
        public int Id { get; set; }
        public string cmd { get; set; }
        public string name { get; set; }
        public Nullable<double> result { get; set; }
        public string last_app { get; set; }
        public string last_heard { get; set; }
        public Nullable<bool> connected { get; set; }
        public string last_handshake_at { get; set; }
        public string deviceID { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
